In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount("/content/gdrive", force_remount= True)

Mounted at /content/gdrive


In [3]:
df = pd.read_csv("/content/gdrive/My Drive/ML_practical/2_Linear_Regression_multivariate/homeprices (1).csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**Data Preprocessing: Fill NA values with median value**

In [4]:
df.bedrooms.median()

4.0

In [5]:
df.bedrooms.mean()

4.2

In [6]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
x = df.drop('price', axis = 'columns')
y = df.price

In [8]:
from sklearn import linear_model
reg = linear_model.LinearRegression()


reg.fit(x,y)

LinearRegression()

In [9]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [10]:
reg.intercept_

221323.00186540396

Find price of home with 3000 sqr fitarea, 3 bedrooms, 40 yrs old

> Indented block



---



In [11]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

Find price of home with 2600 sqr fitarea, 4 bedrooms, 5 yrs old

---



In [12]:
reg.predict([[2600,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590082.28168355])

In [13]:
112.06244194*4 + 23388.88007794*4 + -3231.71790863*4 + 221323.00186540396


302399.90031040396