In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive


In [5]:
df = pd.read_csv('/content/gdrive/My Drive/ML_practical/7_Naive_Bayes/titanic.csv')
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [6]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis = 'columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [7]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [8]:
#inputs.Sex = inputs.Sex.map({'male : 1, 'female':2})

In [9]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

female  male
0       0     1
1       1     0
2       1     0

In [10]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

**i am dropping male columns as erll because of dummy variable trap theory. One column in enough to represent male vs female**

In [11]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [12]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [13]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [14]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [16]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [17]:
model.fit(x_train, y_train)

GaussianNB()

In [18]:
model.score(x_test,y_test)

0.7798507462686567

In [19]:
x_test[0:10]

Pclass        Age     Fare  female
290       1  26.000000  78.8500       1
424       3  18.000000  20.2125       0
675       3  18.000000   7.7750       0
839       1  29.699118  29.7000       0
472       2  33.000000  27.7500       1
152       3  55.500000   8.0500       0
525       3  40.500000   7.7500       0
108       3  38.000000   7.8958       0
141       3  22.000000   7.7500       1
214       3  29.699118   7.7500       0

In [20]:
y_test[0:10]

290    1
424    0
675    0
839    1
472    1
152    0
525    0
108    0
141    1
214    0
Name: Survived, dtype: int64

In [21]:
model.predict(x_test[0:10])

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [22]:
model.predict_proba(x_test[0:10])

array([[0.01525356, 0.98474644],
       [0.96370461, 0.03629539],
       [0.96304312, 0.03695688],
       [0.74402832, 0.25597168],
       [0.2600115 , 0.7399885 ],
       [0.96827186, 0.03172814],
       [0.97076143, 0.02923857],
       [0.97064974, 0.02935026],
       [0.43315578, 0.56684422],
       [0.96898887, 0.03101113]])

**calculate the score using cross validation**

In [23]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train,y_train, cv=5)

array([0.752     , 0.736     , 0.808     , 0.78225806, 0.75      ])

In [24]:
from sklearn.metrics import classification_report

model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_train)

In [25]:
Classification_report = classification_report(y_train, y_pred)

In [26]:
print("Cross-validation Scores:", cross_val_score)
print("Classification Report:")
print(Classification_report)


Cross-validation Scores: <function cross_val_score at 0x7fbf8c9df640>
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.81      0.82       381
           1       0.71      0.72      0.72       242

    accuracy                           0.78       623
   macro avg       0.77      0.77      0.77       623
weighted avg       0.78      0.78      0.78       623



In [27]:
# target_name=['0','1']
# print(Classification_report(y_test,y_pred))